# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 262f3ec2ed13dcf4086f603ed9590451624b241204d05e823899dbbe89be23bbd760bc93464869c9d0c1f3f7382e30dca8f86def89940e037f66fed9c08ab280

test:
  secret_key_base: 0bc9d70640e0dd85fabf38adfb36f13618af3bf65df456a90953e607d68dc9c9f2aee4a7e03bda82bcc9b4948dbb090af6f5b1b702d805cea70a7fe9382f9c05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
